#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '11.0.0'
    cuda10:
        version: '10.1.243'
    cuda11:
        version: '11.4.1'
    cuda12:
        version: '12.1.1'
    hip:
        version: '5.5.30571'
    hiprt:
        version: '2.0.3a134c7'
    optix:
        version: '7.3.0'
    ocloc:
        version: '101.4032'
    cmake:
        default:
            version: any
            overrides: {"WITH_CYCLES_DEVICE_ONEAPI": "OFF"}
        darwin-arm64:
            overrides: {"WITH_CYCLES_DEVICE_ONEAPI": "OFF"}
        darwin-x86_64:
            overrides: {"WITH_CYCLES_DEVICE_ONEAPI": "OFF"}
        linux-x86_64:
            overrides: {"WITH_CYCLES_DEVICE_ONEAPI": "OFF"}
        windows-amd64:
            overrides: {"WITH_CYCLES_DEVICE_ONEAPI": "OFF"}
